#!/bin/bash

# AI 资讯自动推送脚本
# 使用方法：./scripts/auto-push.sh

set -e

# 获取脚本所在目录的父目录（项目根目录）
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$( cd "$SCRIPT_DIR/.." && pwd )"

cd "$PROJECT_ROOT"

# 加载环境变量
if [ -f .env ]; then
    export $(cat .env | grep -v '^#' | grep -v '^$' | xargs)
fi

# 检查是否有 token
if [ -z "$GITHUB_TOKEN" ]; then
    echo "❌ 错误：未找到 GITHUB_TOKEN"
    echo "请在项目根目录的 .env 文件中配置 GITHUB_TOKEN"
    echo ""
    echo "配置方法："
    echo "1. 复制 .env.example 为 .env"
    echo "2. 在 .env 中填入你的 GitHub Personal Access Token"
    exit 1
fi

# 检查是否有更改
if [ -z "$(git status --porcelain)" ]; then
    echo "✅ 没有需要提交的更改"
    exit 0
fi

# 获取当前日期
DATE=$(date +%Y-%m-%d)

# Git 操作
echo "📦 添加所有更改..."
git add .

echo "💾 提交更改..."
git commit -m "Add AI news analysis for $DATE

Auto-generated by AI workflow
- AI Programming
- Generative AI
- AI Chips
- Quantum Computing
- Robotics" || true

echo "🚀 推送到 GitHub..."
# 使用 token 推送（不会暴露在命令行历史中）
git push https://${GITHUB_TOKEN}@github.com/ZhipingYang/News.git master 2>&1 | grep -v "$GITHUB_TOKEN" || true

echo ""
echo "✅ 推送成功！"
echo "🌐 网站将在 2-3 分钟后更新：https://zhipingyang.github.io/News/"

