#!/bin/bash

# AI 资讯自动推送脚本
# 优先使用GitHub CLI，Token作为fallback
# 使用方法：./scripts/auto-push.sh

set -e

# 获取脚本所在目录的父目录（项目根目录）
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$( cd "$SCRIPT_DIR/.." && pwd )"

cd "$PROJECT_ROOT"

# 检查是否有更改
if [ -z "$(git status --porcelain)" ]; then
    echo "✅ 没有需要提交的更改"
    exit 0
fi

# 获取当前日期
DATE=$(date +%Y-%m-%d)

# Git 操作
echo "📦 添加所有更改..."
git add .

echo "💾 提交更改..."
git commit -m "Add AI news analysis for $DATE

Auto-generated by AI workflow
- AI Programming
- Generative AI
- AI Chips
- Quantum Computing
- Robotics" || true

echo "🚀 推送到 GitHub..."

# 方法1：尝试使用GitHub CLI（推荐）
if command -v gh &> /dev/null; then
    echo "使用GitHub CLI推送..."
    if gh auth status &> /dev/null; then
        git push origin master 2>&1
        if [ $? -eq 0 ]; then
            echo ""
            echo "✅ 推送成功！（使用GitHub CLI）"
            echo "🌐 网站将在 2-3 分钟后更新：https://zhipingyang.github.io/News/"
            exit 0
        else
            echo "⚠️  GitHub CLI推送失败，尝试Token方式..."
        fi
    else
        echo "⚠️  GitHub CLI未登录，尝试Token方式..."
    fi
else
    echo "ℹ️  GitHub CLI未安装，使用Token方式..."
fi

# 方法2：使用Token推送（fallback）
# 加载环境变量
if [ -f .env ]; then
    export $(cat .env | grep -v '^#' | grep -v '^$' | xargs)
fi

if [ -z "$GITHUB_TOKEN" ]; then
    echo ""
    echo "❌ 推送失败！"
    echo ""
    echo "请选择以下任一方式配置："
    echo ""
    echo "方式1：使用GitHub CLI（推荐）"
    echo "  brew install gh"
    echo "  gh auth login"
    echo ""
    echo "方式2：使用Personal Access Token"
    echo "  1. 创建.env文件"
    echo "  2. 添加：GITHUB_TOKEN=your_token_here"
    echo "  3. 生成token：https://github.com/settings/tokens"
    echo ""
    echo "方式3：手动推送"
    echo "  git push origin master"
    exit 1
fi

# 使用token推送
echo "使用Token推送..."
REPO_URL=$(git remote get-url origin | sed 's/.*github\.com[:/]\(.*\)\.git/\1/' || echo "ZhipingYang/News")
git push https://${GITHUB_TOKEN}@github.com/${REPO_URL}.git master 2>&1 | grep -v "$GITHUB_TOKEN"

if [ $? -eq 0 ]; then
    echo ""
    echo "✅ 推送成功！（使用Token）"
    echo "🌐 网站将在 2-3 分钟后更新：https://zhipingyang.github.io/News/"
else
    echo ""
    echo "❌ Token推送也失败！"
    echo ""
    echo "请尝试："
    echo "1. 检查Token权限（需要repo权限）"
    echo "2. 手动推送：git push origin master"
    echo "3. 查看详细文档：docs/TROUBLESHOOTING.md"
    exit 1
fi
